Repository Wireless-Innovation-Forum/Spectrum-Access-System, pull requests merged in 2018-06, with the labels that each got.

#735 Fix IPR2 issue caused by temporary DPA KML
  src/harness/reference_models/dpa/dpa_mgr.py
  src/harness/reference_models/dpa/dpa_mgr_test.py
  src/harness/reference_models/geo/zones.py
Labels: reference model, reviewer:federated

#734 Updates the cert generation scripts:
  src/harness/certs/generate_fake_certs.sh
  src/harness/certs/generate_sas_cert.sh
Labels: needs reviewer

#738 Minor fixes - no effects on test harness
  src/harness/reference_models/geo/tropoclim.py
  src/harness/test_main.py
Labels: needs reviewer

#739 Fix flakiness in test cases which inject PPAs
  src/harness/util.py
Labels: reviewer:federated

#740 Improved logging for DPA and IAP aggr interference
  src/harness/reference_models/dpa/dpa_mgr.py
  src/harness/reference_models/dpa/dpa_mgr_example.py
  src/harness/reference_models/dpa/move_list.py
  src/harness/reference_models/iap/iap.py
  src/harness/reference_models/interference/aggregate_interference.py
  src/harness/testcases/WINNF_FT_S_MCP_testcase.py
Labels: needs reviewer

#741 MCP updates
  src/harness/testcases/WINNF_FT_S_EPR_testcase.py
  src/harness/testcases/WINNF_FT_S_FPR_testcase.py
  src/harness/testcases/WINNF_FT_S_GPR_testcase.py
  src/harness/testcases/WINNF_FT_S_MCP_testcase.py
  src/harness/testcases/WINNF_FT_S_PPR_testcase.py
Labels: reviewer:federated

#743 Update FDB.2 to use the latest P-DPA format.
  src/harness/testcases/testdata/fdb_2/FDB_2_Portal_DPAs.kml
  src/harness/testcases/testdata/fdb_2/modified_FDB_2_Portal_DPAs.kml
Labels: needs reviewer

#745 Use "raise" instead of "raise e" to help with debugging.
  src/harness/test_harness_objects.py
  src/harness/testcases/WINNF_FT_S_DRG_testcase.py
  src/harness/testcases/WINNF_FT_S_FAD_testcase.py
  src/harness/testcases/WINNF_FT_S_FDB_testcase.py
  src/harness/testcases/WINNF_FT_S_GRA_testcase.py
  src/harness/testcases/WINNF_FT_S_HBT_testcase.py
  src/harness/testcases/WINNF_FT_S_MCP_testcase.py
  src/harness/testcases/WINNF_FT_S_RLQ_testcase.py
  src/harness/testcases/WINNF_FT_S_SIQ_testcase.py
Labels: needs reviewer

#746 Correct FDB.3 default config, and add database url injection
  src/harness/testcases/WINNF_FT_S_FDB_testcase.py
Labels: needs reviewer

#747 Use same config for FDB.3 and FDB.8
  src/harness/testcases/WINNF_FT_S_FDB_testcase.py
  src/harness/testcases/testdata/fdb_3/FDB_3_default_allsitedata
  src/harness/testcases/testdata/fdb_8/FDB_8_default_allsitedata.json
Labels: needs reviewer

#748 Bug fix on the ESC neighborhood for CatA during IAP.
  src/harness/reference_models/interference/interference.py
Labels: reference model, reviewer:federated

#750 Use all extensions during SAS cert generation.
  src/harness/certs/generate_sas_cert.sh
Labels: reviewer:federated

#752 add simple MCP check and update FAD.2 device 4
  src/harness/testcases/WINNF_FT_S_EPR_testcase.py
  src/harness/testcases/WINNF_FT_S_FAD_testcase.py
  src/harness/testcases/WINNF_FT_S_FPR_testcase.py
  src/harness/testcases/WINNF_FT_S_GPR_testcase.py
  src/harness/testcases/WINNF_FT_S_MCP_testcase.py
  src/harness/testcases/WINNF_FT_S_PPR_testcase.py
Labels: reviewer:federated, reviewer:google

#755 Fix device_c heightType and location for a contour with a testable signal level.
  src/harness/testcases/WINNF_FT_S_PCR_testcase.py
Labels: needs reviewer

#753 Fix default config for FDB.1
  src/harness/testcases/WINNF_FT_S_FDB_testcase.py
  src/harness/testcases/testdata/fdb_1/FDB_1_ground_based_exclusion_zones.kml
  src/harness/testcases/testdata/fdb_1/modified_FDB_1_ground_based_exclusion_zones.kml
Labels: needs reviewer

#754 Fix FDB.4 default config
  src/harness/testcases/WINNF_FT_S_FDB_testcase.py
  src/harness/testcases/testdata/fdb_4/FDB_4_default_allsitedata.json
  src/harness/testcases/testdata/fdb_4/modified_FDB_4_default_allsitedata.json
Labels: needs reviewer

#744 Update IPR test cases according to the latest spec changes
  src/harness/reference_models/dpa/dpa_mgr.py
  src/harness/reference_models/geo/zones.py
  src/harness/testcases/WINNF_FT_S_IPR_testcase.py
Labels: reviewer:red

#758 Remove erroneous line from IPR.7.
  src/harness/testcases/WINNF_FT_S_IPR_testcase.py
Labels: reviewer:federated

#757 Improve GridPolygon.
  src/harness/reference_models/geo/utils.py
  src/harness/reference_models/geo/utils_test.py
Labels: reference model, reviewer:federated

#759 By default, allow NLCD voting
  src/harness/reference_models/geo/nlcd.py
Labels: needs reviewer

#760 PCR: avoid multipolygons in default configurations.
  src/harness/reference_models/geo/testdata/json/test_shrink.json
  src/harness/reference_models/geo/utils.py
  src/harness/reference_models/geo/utils_test.py
  src/harness/testcases/WINNF_FT_S_PCR_testcase.py
Labels: reviewer:federated

#756 Trigger DPA activation correctly in MCP.1
  src/harness/testcases/WINNF_FT_S_MCP_testcase.py
Labels: reviewer:federated

#763 Fix ShrinkAndCleanPolygon to actually shrink and not expand.
  src/harness/reference_models/geo/utils.py
  src/harness/reference_models/geo/utils_test.py
Labels: reference model, reviewer:red

#765 Fixes invalid configs for FDB_3 and FDB_8.
  src/harness/testcases/WINNF_FT_S_FDB_testcase.py
Labels: needs reviewer

#767 Improved logging for IAP aggregation interference checking
  src/harness/testcases/WINNF_FT_S_MCP_testcase.py
Labels: needs reviewer

#764 Fix BPR.2 Issue by adding Multi_lineString case
  src/harness/reference_models/geo/utils.py
  src/harness/reference_models/geo/utils_test.py
Labels: needs reviewer, reference model, reviewer:google

#769 Fix Chris Anderson's issue #768
  src/harness/testcases/WINNF_FT_S_PAT_testcase.py
Labels: reviewer:red

#776 Fix documentation for DPA.
  src/harness/reference_models/dpa/README.md
  src/harness/reference_models/dpa/dpa_builder.py
  src/harness/reference_models/dpa/dpa_mgr.py
Labels: reference model

#773 IAP propag cache: avoid excessive memory use
  src/harness/reference_models/propagation/wf_hybrid.py
Labels: needs reviewer, reference model

#772 Adding less stringent check to PPA creation on assertppacreationfailure function
  src/harness/sas_testcase.py
  src/harness/testcases/WINNF_FT_S_PCR_testcase.py
Labels: reviewer:google

#771 Adding 501 as a valid response code to 2nd CBSD in first check for FDB4 default config
  src/harness/testcases/WINNF_FT_S_FDB_testcase.py
Labels: reviewer:google
