Repository Wireless-Innovation-Forum/Spectrum-Access-System, pull requests merged in 2018-03, with the labels that each got.

#441 fix SCS.10 and SDS.10 issues
  cert/openssl.cnf
  src/harness/certs/generate_fake_certs.sh
Labels: reviewer:sony

#448 assaneRed_Fix_MES_2
  src/harness/testcases/WINNF_FT_S_MES_testcase.py
Labels: reviewer:commscope

#450 NEW SSS test cases with new ID: 1 to 5
  src/harness/fake_sas.py
  src/harness/sas.py
  src/harness/sas_interface.py
  src/harness/security_testcase.py
  src/harness/testcases/WINNF_FT_S_SCS_testcase.py
  src/harness/testcases/WINNF_FT_S_SDS_testcase.py
  src/harness/testcases/WINNF_FT_S_SSS_testcase.py
Labels: needs reviewer, reviewer:federated

#436 fix for SSS test cases do not inject peer SAS (issue #431)
  src/harness/fake_sas.py
  src/harness/sas_interface.py
  src/harness/testcases/WINNF_FT_S_SSS_testcase.py
  src/harness/testcases/configs/test_WINNF_FT_S_SSS_12/default.config
  src/harness/testcases/configs/test_WINNF_FT_S_SSS_13/default.config
  src/harness/testcases/configs/test_WINNF_FT_S_SSS_14/default.config
  src/harness/testcases/configs/test_WINNF_FT_S_SSS_6/default.config
  src/harness/testcases/configs/test_WINNF_FT_S_SSS_7/default.config
  src/harness/testcases/configs/test_WINNF_FT_S_SSS_8/default.config
  src/harness/testcases/configs/test_WINNF_FT_S_SSS_9/default.config
  src/harness/util.py
Labels: reviewer:google

#443 SSS.10,15,17,18 submission
  cert/openssl.cnf
  schema/ActivityDumpFile.schema.json
  schema/FullActivityDump.schema.json
  schema/verify_schema.py
  src/harness/certs/generate_fake_certs.sh
  src/harness/fake_sas.py
  src/harness/sas.py
  src/harness/sas_interface.py
  src/harness/sas_testcase.py
  src/harness/testcases/WINNF_FT_S_SSS_testcase.py
  src/harness/util.py
Labels: reviewer:google

#454 remove duplicate getCertificateFingerprint
  src/harness/util.py
Labels: reviewer:google

#456 Commit again SDS-6-10, 12-15 deleted in PR#450 due to a bad merge
  src/harness/testcases/WINNF_FT_S_SDS_testcase.py
Labels: reviewer:federated

#457 Fix REG.12 and typo in esc_sensor_record_0.json
  src/harness/testcases/WINNF_FT_S_REG_testcase.py
  src/harness/testcases/testdata/esc_sensor_record_0.json
Labels: reviewer:sony

#435 New PR for SAS Test Harness and FAD.2
  src/harness/fake_sas.py
  src/harness/sas.cfg
  src/harness/sas_test_harness.py
  src/harness/testcases/WINNF_FT_S_FAD_testcase.py
  src/harness/testcases/configs/test_WINNF_FT_S_FAD_2/default.config
  src/harness/util.py
Labels: reviewer:google

#396 Federated Wireless delivered SIQ.12
  src/harness/sas_testcase.py
  src/harness/testcases/WINNF_FT_S_SIQ_testcase.py
  src/harness/testcases/configs/test_WINNF_FT_S_SIQ_12/default.config
Labels: reviewer:commscope, reviewer:google

#459 Fix palRecords in GRA.17 - config.
  src/harness/testcases/WINNF_FT_S_GRA_testcase.py
Labels: reviewer:federated

#458 Clean up fake_sas.py
  src/harness/fake_sas.py
Labels: needs reviewer

#461 adding "cbsd/" prefix in generateCbsdReferenceId()
  src/harness/sas_test_harness.py
Labels: reviewer:google

#452 Implement fix of median to mean in Hybrid model.
  src/harness/reference_models/propagation/wf_hybrid.py
  src/harness/reference_models/propagation/wf_hybrid_test.py
Labels: needs reviewer, reference model

#440 GRA.5 and 6 rework
  src/harness/sas_test_harness.py
  src/harness/testcases/WINNF_FT_S_GRA_testcase.py
Labels: reviewer:google

#464 Remove the stuff relating to "SasImplementationRecord"
  src/harness/sas.py
  src/harness/sas_interface.py
Labels: reviewer:federated

#389 Federated Wireless added EXZ test cases
  src/harness/fake_sas.py
  src/harness/sas.py
  src/harness/sas_interface.py
  src/harness/testcases/WINNF_FT_S_EXZ_testcase.py
  src/harness/testcases/testdata/exz_record_0.json
  src/harness/testcases/testdata/exz_record_1.json
Labels: reviewer:google, reviewer:sony

#465 add configs folder to gitignore
  src/harness/testcases/.gitignore
  src/harness/testcases/configs/test_WINNF_FT_S_DRG_6/default.config
  src/harness/testcases/configs/test_WINNF_FT_S_FAD_2/default.config
  src/harness/testcases/configs/test_WINNF_FT_S_GRA_17/default.config
  src/harness/testcases/configs/test_WINNF_FT_S_HBT_10/default.config
  src/harness/testcases/configs/test_WINNF_FT_S_REG_11/default.config
  src/harness/testcases/configs/test_WINNF_FT_S_REG_12/default.config
  src/harness/testcases/configs/test_WINNF_FT_S_REG_13/default.config
  src/harness/testcases/configs/test_WINNF_FT_S_RLQ_6/default.config
  src/harness/testcases/configs/test_WINNF_FT_S_SIQ_12/default.config
  src/harness/testcases/configs/test_WINNF_FT_S_SSS_12/default.config
  src/harness/testcases/configs/test_WINNF_FT_S_SSS_13/default.config
  src/harness/testcases/configs/test_WINNF_FT_S_SSS_14/default.config
  src/harness/testcases/configs/test_WINNF_FT_S_SSS_6/default.config
  src/harness/testcases/configs/test_WINNF_FT_S_SSS_7/default.config
  src/harness/testcases/configs/test_WINNF_FT_S_SSS_8/default.config
  src/harness/testcases/configs/test_WINNF_FT_S_SSS_9/default.config
Labels: reviewer:google

#463 Added Exception for PPA Census Tract MultiPolygon
  README.md
  src/harness/reference_models/geo/census_tract.py
  src/harness/reference_models/geo/vincenty.py
  src/harness/reference_models/ppa/ppa.py
  src/harness/reference_models/ppa/ppa_example.py
Labels: reference model, reviewer:google

#471 Make heartbeat_request to be a list, fix typo
  src/harness/testcases/WINNF_FT_S_HBT_testcase.py
Labels: reviewer:federated

#470 Move the documentation from sas_interface to sas_testcase.
  src/harness/sas_interface.py
  src/harness/sas_testcase.py
Labels: reviewer:federated

#477 Add polygon comparison routines.
  src/harness/reference_models/geo/utils.py
  src/harness/reference_models/geo/utils_test.py
Labels: reference model, reviewer:red

#478 Fix dpaId - Added an underscore (Eg: 'east_dpa_6')
  src/harness/testcases/WINNF_FT_S_GRA_testcase.py
  src/harness/testcases/WINNF_FT_S_HBT_testcase.py
  src/harness/testcases/WINNF_FT_S_SIQ_testcase.py
Labels: needs reviewer

#484 Add "antennaAzimuth" to Cat A device json files.
  src/harness/testcases/testdata/device_a.json
  src/harness/testcases/testdata/device_c.json
  src/harness/testcases/testdata/device_e.json
  src/harness/testcases/testdata/device_f.json
  src/harness/testcases/testdata/device_g.json
Labels: reviewer:federated

#479 Fix conditionalRegistrationData
  src/harness/sas_testcase.py
  src/harness/testcases/WINNF_FT_S_DRG_testcase.py
  src/harness/testcases/WINNF_FT_S_GRA_testcase.py
  src/harness/testcases/WINNF_FT_S_HBT_testcase.py
  src/harness/testcases/WINNF_FT_S_REG_testcase.py
  src/harness/testcases/WINNF_FT_S_RLQ_testcase.py
  src/harness/testcases/WINNF_FT_S_SIQ_testcase.py
Labels: needs reviewer

#469 Simple CRL server using native openssl CRL capabilities
  cert/openssl.cnf
  src/harness/CRLServer-README.md
  src/harness/certs/generate_fake_certs.sh
  src/harness/certs/revoke_and_generate_crl.sh
  src/harness/simple_crl_server.py
Labels: reviewer:google

#472 peer SAS duplicate grant purging reference model
  src/harness/reference_models/inter_sas_duplicate_grant/__init__.py
  src/harness/reference_models/inter_sas_duplicate_grant/inter_sas_duplicate_grant.py
Labels: reference model, reviewer:google

#405 MCP.1 configuration portion
  src/harness/testcases/WINNF_FT_S_MCP_testcase.py
  src/harness/testcases/testdata/cbsd_0.json
  src/harness/testcases/testdata/cbsd_1.json
  src/harness/testcases/testdata/cbsd_2.json
  src/harness/testcases/testdata/cbsd_3.json
  src/harness/testcases/testdata/cbsd_4.json
  src/harness/testcases/testdata/cbsd_5.json
  src/harness/testcases/testdata/grant_1.json
  src/harness/testcases/testdata/grant_2.json
  src/harness/testcases/testdata/grant_3.json
Labels: reviewer:commscope, reviewer:google

#487 Improve geo.utils module.
  src/harness/reference_models/geo/utils.py
  src/harness/reference_models/geo/utils_test.py
  src/harness/reference_models/ppa/ppa.py
Labels: needs reviewer, reference model, reviewer:federated

#485 Full Activity Dump Object
  README.md
  src/harness/README.md
  src/harness/full_activity_dump.py
  src/harness/full_activity_dump_helper.py
  src/harness/full_activity_dump_helper_test.py
  src/harness/full_activity_dump_integration_test.py
  src/harness/full_activity_dump_test.py
  src/harness/request_handler.py
  src/harness/sas.py
  src/harness/sas_test_harness.py
  src/harness/util.py
Labels: reviewer:federated

#475 Pre IAP
  src/harness/reference_models/pre_iap_filtering/__init__.py
  src/harness/reference_models/pre_iap_filtering/pre_iap_filtering.py
Labels: reference model, reviewer:google

#491 remove unnecessary files
  src/harness/testcases/testdata/cbsd_0.json
  src/harness/testcases/testdata/cbsd_1.json
  src/harness/testcases/testdata/cbsd_2.json
  src/harness/testcases/testdata/cbsd_3.json
  src/harness/testcases/testdata/cbsd_4.json
  src/harness/testcases/testdata/cbsd_5.json
Labels: reviewer:google

#493 Restore QueryPropagationAndAntennaModel method
  src/harness/sas.py
Labels: needs reviewer, reference model

#404 Federated Wireless delivered the following key objects: CBSD, Grant, …
  src/harness/common_types.py
  src/harness/sas_testcase.py
  src/harness/test_harness_objects.py
Labels: reviewer:google

#490 small update related to wait for DPA step
  src/harness/testcases/WINNF_FT_S_GRA_testcase.py
  src/harness/testcases/WINNF_FT_S_HBT_testcase.py
Labels: reviewer:google

#499 Correct the documentation for registration_request
  src/harness/sas_testcase.py
Labels: needs reviewer, reviewer:federated

#494 split the interference module out of IAP per reviewer's suggestion
  src/harness/reference_models/interference/interference.py
Labels: needs reviewer, reference model, reviewer:google
