Repository Wireless-Innovation-Forum/Spectrum-Access-System, pull requests merged in 2018-10, with the labels that each got.

#813 Update FDB 5 and 6 expiration dates to 2028-09-23
  src/harness/testcases/WINNF_FT_S_FDB_testcase.py
  src/harness/testcases/testdata/fdb_5/l_micro.zip
  src/harness/testcases/testdata/fdb_6/l_micro.zip
  src/harness/testcases/testdata/fdb_6/modified_l_micro.zip
Labels: reviewer:federated

#817 DRG.6 remove registered CBSDs from second preload conditional data
  src/harness/testcases/WINNF_FT_S_DRG_testcase.py
Labels: reviewer:google

#820 EHata: Cleanup of the float -> double switch.
  src/harness/reference_models/propagation/ehata/its/ExtendedHata.cpp
  src/harness/reference_models/propagation/ehata/its/FindHorizons.cpp
  src/harness/reference_models/propagation/ehata/its/FindQuantile.cpp
  src/harness/reference_models/propagation/ehata/its/FineRollingHillyTerrainCorectionFactor.cpp
  src/harness/reference_models/propagation/ehata/its/GeneralSlopeCorrectionFactor.cpp
  src/harness/reference_models/propagation/ehata/its/IsolatedRidgeCorrectionFactor.cpp
  src/harness/reference_models/propagation/ehata/its/LeastSquares.cpp
  src/harness/reference_models/propagation/ehata/its/MedianBasicPropLoss.cpp
  src/harness/reference_models/propagation/ehata/its/MedianRollingHillyTerrainCorrectionFactor.cpp
  src/harness/reference_models/propagation/ehata/its/MixedPathCorrectionFactor.cpp
  src/harness/reference_models/propagation/ehata/its/PreprocessTerrainPath.cpp
  src/harness/reference_models/propagation/ehata/its/ehata.h
Labels: reference model, reviewer:commscope, reviewer:federated

#821 EHata: Cleanup Average terrain code for the NTIA compatibility mode.
  src/harness/reference_models/propagation/ehata/its/PreprocessTerrainPath.cpp
  src/harness/reference_models/propagation/ehata/its/test/test-inputs-wfmod.csv
Labels: reference model, reviewer:commscope, reviewer:federated

#819 EHata: Fix Fine Rolling Hill correction.
  src/harness/reference_models/propagation/ehata/its/FineRollingHillyTerrainCorectionFactor.cpp
  src/harness/reference_models/propagation/ehata/its/test/test-inputs-wfmod.csv
  src/harness/reference_models/propagation/wf_hybrid_test.py
Labels: reference model, reviewer:commscope, reviewer:federated

#826 Add additional debugging information to some of the protocol tests.
  src/harness/testcases/WINNF_FT_S_DRG_testcase.py
  src/harness/testcases/WINNF_FT_S_GRA_testcase.py
  src/harness/testcases/WINNF_FT_S_REG_testcase.py
  src/harness/testcases/WINNF_FT_S_RLQ_testcase.py
Labels: reviewer:sony

#829 Update DPAs KML from NTIA
  data/ntia/DPA_KML_v1.04.pdf
  data/ntia/E-DPAs.kml
  data/ntia/P-DPAs.kml
Labels: reviewer:federated

#831 Miscellaneous tool and doc provided to ITS by mail.
  src/harness/reference_models/tools/cata_max_height.py
  src/harness/reference_models/tools/docs/dpa_config/DPA_configuration_in_MCP.pdf
  src/harness/reference_models/tools/docs/dpa_config/mcp1_config.json
Labels: reviewer:commscope

#830 Add more logging of A_DPA, A_DPA_ref, and keep lists to DPA manager
  src/harness/reference_models/dpa/dpa_mgr.py
Labels: reviewer:commscope, reviewer:red

#832 Fix DPA logging for "no grants in neighborhood" case
  src/harness/reference_models/dpa/dpa_mgr.py
Labels: reviewer:sony

#835 Batch conditional reg data
  src/harness/test_harness_objects.py
Labels: reviewer:commscope

#836 Fix error creating PAL record for FIPS codes with leading zeroes
  src/harness/util.py
Labels: reviewer:sony
