Repository Wireless-Innovation-Forum/Spectrum-Access-System, pull requests merged in 2018-08, with the labels that each got.

#792 Fix Server Shutdown between Tests
  src/harness/database.py
  src/harness/sas_test_harness.py
  src/harness/sas_testcase.py
  src/harness/testcases/WINNF_FT_S_EPR_testcase.py
  src/harness/testcases/WINNF_FT_S_FAD_testcase.py
  src/harness/testcases/WINNF_FT_S_FDB_testcase.py
  src/harness/testcases/WINNF_FT_S_FPR_testcase.py
  src/harness/testcases/WINNF_FT_S_GPR_testcase.py
  src/harness/testcases/WINNF_FT_S_GRA_testcase.py
  src/harness/testcases/WINNF_FT_S_IPR_testcase.py
  src/harness/testcases/WINNF_FT_S_MCP_testcase.py
  src/harness/testcases/WINNF_FT_S_MES_testcase.py
  src/harness/testcases/WINNF_FT_S_PPR_testcase.py
  src/harness/testcases/WINNF_FT_S_WDB_testcase.py
Labels: reviewer:google

#795 Use the right grant request & maxEirp in the interference calculation.
  src/harness/testcases/WINNF_FT_S_BPR_testcase.py
Labels: reviewer:red

#796 Update E-DPAs.kml to have compliant KML "holes".
  data/ntia/E-DPAs.kml
Labels: reference model, reviewer:red

#793 Implement changes to IPR.7 requested by WG4.
  src/harness/testcases/WINNF_FT_S_IPR_testcase.py
Labels: needs reviewer

#800 Fix bug where the heartbeat request was used rather than the heartbeat response
  src/harness/test_harness_objects.py
Labels: reviewer:federated

#801 Renew grants with every heartbeat in functional tests
  src/harness/test_harness_objects.py
Labels: reviewer:commscope
