Repository Wireless-Innovation-Forum/Spectrum-Access-System, pull requests merged in 2018-04, with the labels that each got.

#496 PPR.1 and 2 submission for review
  src/harness/testcases/WINNF_FT_S_PPR_testcase.py
Labels: reviewer:google

#492 initial submission of EPR
  src/harness/testcases/WINNF_FT_S_EPR_testcase.py
Labels: reviewer:google

#503 Fix small set of issues on previous #476
  src/harness/reference_models/examples/benchmark/time_dpa.py
  src/harness/reference_models/examples/entities.py
  src/harness/reference_models/geo/zones.py
  src/harness/reference_models/geo/zones_test.py
  src/harness/reference_models/ppa/ppa_test.py
Labels: reference model

#506 QPR.2 and QPR.6 tests
  src/harness/testcases/WINNF_FT_S_QPR_testcase.py
Labels: needs reviewer

#497 GPR.1 through 3 submission for review
  src/harness/testcases/WINNF_FT_S_GPR_testcase.py
Labels: reviewer:google

#508 Miscellaneous test harness fixes
  src/harness/full_activity_dump_helper.py
  src/harness/full_activity_dump_integration_test.py
  src/harness/sas_test_harness.py
Labels: needs reviewer

#512 Fixing device location - longitude
  src/harness/testcases/WINNF_FT_S_EPR_testcase.py
Labels: needs reviewer

#480 rework of PCR.1
  src/harness/fake_sas.py
  src/harness/reference_models/ppa/ppa.py
  src/harness/sas.py
  src/harness/sas_interface.py
  src/harness/testcases/WINNF_FT_S_PCR_testcase.py
Labels: reviewer:google

#513 Small fix to SIQ3
  src/harness/testcases/WINNF_FT_S_SIQ_testcase.py
Labels: needs reviewer

#515 Injecting FCC IDs for GRA5 before CPAS so SUUT will know about them
  src/harness/testcases/WINNF_FT_S_GRA_testcase.py
Labels: reviewer:federated

#514 fix PCR.1 errors
  src/harness/sas.py
  src/harness/testcases/WINNF_FT_S_PCR_testcase.py
Labels: needs reviewer

#516 aggregate interference unit tests
  src/harness/reference_models/examples/testutils.py
  src/harness/reference_models/interference/aggregate_interference_test.py
  src/harness/reference_models/interference/test_data/cbsd_th1_ut.json
  src/harness/reference_models/interference/test_data/cbsd_uut_ut.json
  src/harness/reference_models/interference/test_data/esc_ut.json
  src/harness/reference_models/interference/test_data/fss_ut.json
  src/harness/reference_models/interference/test_data/gwpz_ut.json
  src/harness/reference_models/interference/test_data/pal_ut.json
  src/harness/reference_models/interference/test_data/ppa_ut.json
  src/harness/reference_models/interference/test_results/aggregate_interference_unit_test_calc_sheet.xlsx
Labels: reference model, reviewer:google

#468 SCS/SDS/SSS.16 implementation based on WG.2 confirmation -- revoked CA is sub-CA
  cert/openssl.cnf
  src/harness/certs/README.md
  src/harness/certs/generate_fake_certs.sh
  src/harness/certs/revoke_and_generate_crl.sh
  src/harness/fake_sas.py
  src/harness/simple_crl_server.py
  src/harness/testcases/README.md
  src/harness/testcases/WINNF_FT_S_SCS_testcase.py
  src/harness/testcases/WINNF_FT_S_SDS_testcase.py
  src/harness/testcases/WINNF_FT_S_SSS_testcase.py
Labels: reviewer:google

#474 WINNF_FT_S_FPR5 testcase
  src/harness/testcases/WINNF_FT_S_FPR_testcase.py
Labels: reviewer:google

#467 SCS/SDS/SSS.11 implementation based on the confirmation of WG.2 on using CRL for blacklisting
  src/harness/certs/README.md
  src/harness/certs/generate_fake_certs.sh
  src/harness/fake_sas.py
  src/harness/testcases/README.md
  src/harness/testcases/WINNF_FT_S_SCS_testcase.py
  src/harness/testcases/WINNF_FT_S_SDS_testcase.py
  src/harness/testcases/WINNF_FT_S_SSS_testcase.py
Labels: reviewer:google

#498 new PPA,GWPZ,FFS+GWBL purge list reference model
  src/harness/reference_models/pre_iap_filtering/pre_iap_filtering.py
  src/harness/reference_models/pre_iap_filtering/pre_iap_filtering_test.py
  src/harness/reference_models/pre_iap_filtering/pre_iap_util.py
  src/harness/reference_models/pre_iap_filtering/testdata/cbsd_0.json
  src/harness/reference_models/pre_iap_filtering/testdata/cbsd_1.json
  src/harness/reference_models/pre_iap_filtering/testdata/cbsd_2.json
  src/harness/reference_models/pre_iap_filtering/testdata/cbsd_3.json
  src/harness/reference_models/pre_iap_filtering/testdata/cbsd_4.json
  src/harness/reference_models/pre_iap_filtering/testdata/cbsd_5.json
  src/harness/reference_models/pre_iap_filtering/testdata/fss_0.json
  src/harness/reference_models/pre_iap_filtering/testdata/fss_1.json
  src/harness/reference_models/pre_iap_filtering/testdata/gwbl_0.json
  src/harness/reference_models/pre_iap_filtering/testdata/gwpz_0.json
  src/harness/reference_models/pre_iap_filtering/testdata/pal_0.json
  src/harness/reference_models/pre_iap_filtering/testdata/ppa_0.json
  src/harness/reference_models/pre_iap_filtering/testdata/testset1/cbsd_0.json
  src/harness/reference_models/pre_iap_filtering/testdata/testset1/cbsd_1.json
  src/harness/reference_models/pre_iap_filtering/testdata/testset1/cbsd_2.json
  src/harness/reference_models/pre_iap_filtering/testdata/testset1/cbsd_3.json
  src/harness/reference_models/pre_iap_filtering/testdata/testset1/cbsd_4.json
  src/harness/reference_models/pre_iap_filtering/testdata/testset1/cbsd_5.json
  src/harness/reference_models/pre_iap_filtering/testdata/testset1/cbsd_bkp.json
  src/harness/reference_models/pre_iap_filtering/testdata/testset1/fss_0.json
  src/harness/reference_models/pre_iap_filtering/testdata/testset1/fss_1.json
  src/harness/reference_models/pre_iap_filtering/testdata/testset1/gwbl_0.json
  src/harness/reference_models/pre_iap_filtering/testdata/testset1/gwpz_0.json
  src/harness/reference_models/pre_iap_filtering/testdata/testset1/pal_0.json
  src/harness/reference_models/pre_iap_filtering/testdata/testset1/pal_1.json
  src/harness/reference_models/pre_iap_filtering/testdata/testset1/pal_2.json
  src/harness/reference_models/pre_iap_filtering/testdata/testset1/ppa_0.json
  src/harness/reference_models/pre_iap_filtering/zone_purge.py
  src/harness/reference_models/pre_iap_filtering/zone_purge_test.py
Labels: reviewer:google

#522 QPR.7
  data/fcc/fcc_field_office_locations.csv
  src/harness/reference_models/geo/CONFIG.py
  src/harness/reference_models/geo/zones.py
  src/harness/testcases/WINNF_FT_S_QPR_testcase.py
Labels: reviewer:federated

#531 Fix broken test due to introduced HTTPError
  src/harness/request_handler.py
  src/harness/testcases/WINNF_FT_S_HBT_testcase.py
  src/harness/testcases/WINNF_FT_S_REG_testcase.py
  src/harness/testcases/WINNF_FT_S_RLQ_testcase.py
  src/harness/testcases/WINNF_FT_S_SSS_testcase.py
Labels: reviewer:red, reviewer:sony

#534 Update CoordinationEvent to coordination
  src/harness/testcases/WINNF_FT_S_FAD_testcase.py
Labels: reviewer:federated

#520 Initial IPR.1 testcase
  src/harness/full_activity_dump_helper_test.py
  src/harness/sas.py
  src/harness/sas_testcase.py
  src/harness/security_testcase.py
  src/harness/test_harness_objects.py
  src/harness/testcases/WINNF_FT_S_IPR_testcase.py
Labels: reviewer:federated

#536 SSS.18: fix certificate injection
  src/harness/testcases/WINNF_FT_S_SSS_testcase.py
Labels: reviewer:google

#535 Sets antennaAzimuth, which is a required field.
  src/harness/testcases/testdata/esc_sensor_record_0.json
Labels: reviewer:federated

#502 PCR2 and 3 submission for review
  src/harness/testcases/WINNF_FT_S_PCR_testcase.py
Labels: reviewer:google

#500 Update SAS UUT Config to Seperate the URLs and version numbers
  src/harness/fake_sas.py
  src/harness/sas.cfg
  src/harness/sas.py
  src/harness/security_testcase.py
Labels: reviewer:google

#545 jc s*s http403fix
  src/harness/testcases/WINNF_FT_S_SCS_testcase.py
  src/harness/testcases/WINNF_FT_S_SDS_testcase.py
  src/harness/testcases/WINNF_FT_S_SSS_testcase.py
Labels: needs reviewer

#539 Fixed FullActivityDumpHelper to correctly use the ssl cert/key
  src/harness/full_activity_dump_helper.py
Labels: reviewer:sony

#550 fix sas TH version
  src/harness/sas_test_harness.py
Labels: reviewer:sony

#547 Avoid injecting the same FCC ID / User ID multiple
  src/harness/sas.py
Labels: reviewer:federated

#523 Prop Models: Implement minimum height of 1m
  src/harness/reference_models/propagation/wf_hybrid.py
  src/harness/reference_models/propagation/wf_hybrid_test.py
  src/harness/reference_models/propagation/wf_itm.py
  src/harness/reference_models/propagation/wf_itm_test.py
Labels: reference model, reviewer:federated

#553 Add TriggerFullActivityDump back into fake sas
  src/harness/fake_sas.py
Labels: needs reviewer, reviewer:federated

#558 fix sas version variable name
  src/harness/testcases/WINNF_FT_S_HBT_testcase.py
  src/harness/testcases/WINNF_FT_S_REG_testcase.py
  src/harness/testcases/WINNF_FT_S_RLQ_testcase.py
Labels: reviewer:google

#557 A few security fixes
  src/harness/security_testcase.py
  src/harness/testcases/WINNF_FT_S_SSS_testcase.py
Labels: needs reviewer

#504 PCR.4 through 7 for review
  src/harness/testcases/WINNF_FT_S_PCR_testcase.py
Labels: reviewer:google

#543 Create config for FPR.2 and FPR.4 testcases
  src/harness/testcases/WINNF_FT_S_FPR_testcase.py
Labels: reviewer:commscope

#560 QPR.8
  src/harness/testcases/WINNF_FT_S_QPR_testcase.py
Labels: reviewer:federated

#562 Change 'TriggerDailyActivitiesImmediately...' to fail immediately
  src/harness/sas_testcase.py
Labels: reviewer:commscope

#537 Initial IPR.2
  src/harness/testcases/WINNF_FT_S_IPR_testcase.py
  src/harness/util.py
Labels: needs reviewer, reviewer:federated
