Repository Wireless-Innovation-Forum/Spectrum-Access-System, pull requests merged in 2018-05, with the labels that each got.

#481 EXZ.2 initial submission
  src/harness/sas.py
  src/harness/sas_interface.py
  src/harness/testcases/WINNF_FT_S_EXZ_testcase.py
Labels: reviewer:google

#567 IPR.6 testcase
  src/harness/fake_sas.py
  src/harness/sas.py
  src/harness/sas_interface.py
  src/harness/testcases/WINNF_FT_S_IPR_testcase.py
Labels: needs reviewer, reviewer:federated

#554 Clean certificate naming
  cert/openssl.cnf
  src/harness/CRLServer-README.md
  src/harness/certs/.gitignore
  src/harness/certs/README.md
  src/harness/certs/generate_fake_certs.sh
  src/harness/certs/revoke_and_generate_crl.sh
  src/harness/fake_sas.py
  src/harness/sas.py
  src/harness/security_testcase.py
  src/harness/test_harness_objects.py
  src/harness/testcases/WINNF_FT_S_EPR_testcase.py
  src/harness/testcases/WINNF_FT_S_GPR_testcase.py
  src/harness/testcases/WINNF_FT_S_MCP_testcase.py
  src/harness/testcases/WINNF_FT_S_PPR_testcase.py
  src/harness/testcases/WINNF_FT_S_SCS_testcase.py
  src/harness/testcases/WINNF_FT_S_SDS_testcase.py
  src/harness/testcases/WINNF_FT_S_SSS_testcase.py
Labels: reviewer:red

#571 Fixing typos in sas.py file
  src/harness/sas.py
Labels: needs reviewer

#563 Ref model support for border tests
  data/fcc/uscabdry_sampled.kmz
  src/data/resample_uscabdry.py
  src/harness/reference_models/geo/utils.py
  src/harness/reference_models/geo/utils_test.py
  src/harness/reference_models/geo/zones.py
  src/harness/reference_models/geo/zones_test.py
Labels: reference model, reviewer:federated

#564 BPR.2
  src/harness/testcases/WINNF_FT_S_BPR_testcase.py
Labels: needs reviewer, reviewer:federated

#569 Reference model general cleanup - Part 1
  src/harness/reference_models/common/data.py
  src/harness/reference_models/common/mpool.py
  src/harness/reference_models/iap/iap.py
  src/harness/reference_models/iap/iap_example.py
  src/harness/reference_models/interference/aggregate_interference.py
  src/harness/reference_models/interference/aggregate_interference_example.py
  src/harness/reference_models/interference/aggregate_interference_test.py
  src/harness/reference_models/interference/interference.py
Labels: reference model, reviewer:commscope

#578 Small speedup: GeodesicSampling routine.
  src/data/resample_uscabdry.py
  src/harness/reference_models/geo/terrain.py
  src/harness/reference_models/geo/vincenty.py
  src/harness/reference_models/geo/vincenty_test.py
Labels: needs reviewer, reference model, reviewer:federated

#579 Add base url support to database
  src/harness/database.py
Labels: needs reviewer, reviewer:federated

#565 Geo data: fix scripts and missing geo tiles
  src/data/README.md
  src/data/legacy/retrieve_ibfs.py
  src/data/legacy/retrieve_uls_files.py
  src/data/nlcd_origin.py
  src/data/retile_nlcd.py
  src/data/retrieve_alaska_ned_extra.py
  src/data/retrieve_fcc_files.py
  src/data/retrieve_itu_files.py
  src/data/retrieve_orig_ned.py
  src/data/retrieve_orig_nlcd.py
  src/harness/reference_models/geo/tiles.py
Labels: reference model, reviewer:red

#583 DPA: Cleanup indentation of move_list module.
  src/harness/reference_models/dpa/move_list.py
  src/harness/reference_models/dpa/move_list_example.py
Labels: reference model, reviewer:nist

#576 integrate FDB.1 with generic database server
  src/harness/fake_sas.py
  src/harness/sas.py
  src/harness/sas_interface.py
  src/harness/testcases/WINNF_FT_S_FDB_testcase.py
  src/harness/testcases/testdata/fdb_1/FDB_1_ground_based_exclusion_zones.kml
  src/harness/testcases/testdata/fdb_1/modified_FDB_1_ground_based_exclusion_zones.kml
Labels: needs reviewer, reviewer:google

#584 EPR_2: Fix typo in GetDefaultDomainProxySSLKeyPath
  src/harness/testcases/WINNF_FT_S_EPR_testcase.py
Labels: needs reviewer, reviewer:federated

#556 PropModel: fix for incidence angle using hzns instead of python
  src/harness/reference_models/geo/testutils.py
  src/harness/reference_models/propagation/itm/itm.py
  src/harness/reference_models/propagation/itm/itm_its_py.cpp
  src/harness/reference_models/propagation/itm/itm_test.py
  src/harness/reference_models/propagation/itm/its/README.md
  src/harness/reference_models/propagation/itm/its/itm.cpp
  src/harness/reference_models/propagation/itm/its/itm.h
  src/harness/reference_models/propagation/itm/its/itm_test.cpp
  src/harness/reference_models/propagation/wf_itm.py
  src/harness/reference_models/propagation/wf_itm_test.py
Labels: reference model, reviewer:commscope, reviewer:federated

#582 FDB.3 database integration
  src/harness/testcases/WINNF_FT_S_FDB_testcase.py
  src/harness/testcases/testdata/fdb_3/FDB_3_default_allsitedata
Labels: needs reviewer, reviewer:federated

#532 Initial IPR.3, IPR.4, and IPR.5
  src/harness/testcases/WINNF_FT_S_IPR_testcase.py
Labels: reviewer:sony

#548 Add 'assertValidConfig' to configurable test cases.
  src/harness/testcases/WINNF_FT_S_DRG_testcase.py
  src/harness/testcases/WINNF_FT_S_EXZ_testcase.py
  src/harness/testcases/WINNF_FT_S_GRA_testcase.py
  src/harness/testcases/WINNF_FT_S_HBT_testcase.py
  src/harness/testcases/WINNF_FT_S_PCR_testcase.py
  src/harness/testcases/WINNF_FT_S_QPR_testcase.py
  src/harness/testcases/WINNF_FT_S_REG_testcase.py
  src/harness/testcases/WINNF_FT_S_RLQ_testcase.py
  src/harness/testcases/WINNF_FT_S_SIQ_testcase.py
Labels: needs reviewer, reviewer:federated

#591 Change comparison for FAD.1 to compare the objects instead of hashing
  src/harness/testcases/WINNF_FT_S_FAD_testcase.py
Labels: reviewer:federated

#575 Add maximum batch size support
  src/harness/fake_sas.py
  src/harness/sas.cfg
  src/harness/sas.py
  src/harness/test_harness_objects.py
Labels: reviewer:commscope

#580 Finalize multiprocessing cleanup.
  src/harness/reference_models/common/mpool.py
  src/harness/reference_models/ppa/ppa.py
  src/harness/test_main.py
Labels: needs reviewer, reference model

#592 adjust device locations of FAD.2 to be closer to the protected entities
  src/harness/testcases/WINNF_FT_S_FAD_testcase.py
Labels: reviewer:google

#590 QPR.5
  src/harness/testcases/WINNF_FT_S_QPR_testcase.py
  src/harness/testcases/testdata/device_j.json
Labels: reviewer:federated

#594 Pre-IAP : Fix and cleanup and fix Pre-IAP model.
  src/harness/reference_models/common/data.py
  src/harness/reference_models/inter_sas_duplicate_grant/__init__.py
  src/harness/reference_models/interference/aggregate_interference.py
  src/harness/reference_models/pre_iap_filtering/fss_purge.py
  src/harness/reference_models/pre_iap_filtering/fss_purge_test.py
  src/harness/reference_models/pre_iap_filtering/inter_sas_duplicate_grant.py
  src/harness/reference_models/pre_iap_filtering/pre_iap_filtering.py
  src/harness/reference_models/pre_iap_filtering/pre_iap_filtering_test.py
  src/harness/reference_models/pre_iap_filtering/pre_iap_util.py
  src/harness/reference_models/pre_iap_filtering/testdata/cbsd_0.json
  src/harness/reference_models/pre_iap_filtering/testdata/cbsd_1.json
  src/harness/reference_models/pre_iap_filtering/testdata/cbsd_2.json
  src/harness/reference_models/pre_iap_filtering/testdata/cbsd_3.json
  src/harness/reference_models/pre_iap_filtering/testdata/cbsd_4.json
  src/harness/reference_models/pre_iap_filtering/testdata/cbsd_5.json
  src/harness/reference_models/pre_iap_filtering/zone_purge.py
  src/harness/reference_models/pre_iap_filtering/zone_purge_test.py
Labels: reference model

#599 Fix WDB test cases
  src/harness/testcases/WINNF_FT_S_WDB_testcase.py
Labels: reviewer:federated

#600 Add back the data files for FDB
  src/harness/testcases/WINNF_FT_S_FDB_testcase.py
  src/harness/testcases/testdata/fdb_4/FDB_4_default_allsitedata.json
  src/harness/testcases/testdata/fdb_4/modified_FDB_4_default_allsitedata.json
  src/harness/testcases/testdata/fdb_5/FDB_5_default_allsitedata.json
  src/harness/testcases/testdata/fdb_5/l_micro.zip
  src/harness/testcases/testdata/fdb_6/FDB_6_default_allsitedata.json
  src/harness/testcases/testdata/fdb_6/l_micro.zip
  src/harness/testcases/testdata/fdb_6/modified_l_micro.zip
  src/harness/testcases/testdata/fdb_8/FDB_8_default_allsitedata.json
Labels: reviewer:federated

#601 using the standard GWPZ data format
  src/harness/reference_models/iap/iap.py
  src/harness/reference_models/iap/test_data/gwpz_0.json
  src/harness/reference_models/iap/test_data/gwpz_1.json
Labels: reviewer:google

#605 Log Common errors in configurations
  src/harness/common_strings.py
  src/harness/test_harness_objects.py
  src/harness/testcases/WINNF_FT_S_DRG_testcase.py
  src/harness/testcases/WINNF_FT_S_EXZ_testcase.py
  src/harness/testcases/WINNF_FT_S_FAD_testcase.py
  src/harness/testcases/WINNF_FT_S_FDB_testcase.py
  src/harness/testcases/WINNF_FT_S_GRA_testcase.py
  src/harness/testcases/WINNF_FT_S_HBT_testcase.py
  src/harness/testcases/WINNF_FT_S_MCP_testcase.py
  src/harness/testcases/WINNF_FT_S_REG_testcase.py
  src/harness/testcases/WINNF_FT_S_RLQ_testcase.py
  src/harness/testcases/WINNF_FT_S_SIQ_testcase.py
Labels: needs reviewer

#607 Resolves issues in FDB.3 and database
  src/harness/database.py
  src/harness/testcases/WINNF_FT_S_FDB_testcase.py
Labels: needs reviewer

#602 MCP.1 w/ refactor
  src/harness/test_harness_objects.py
  src/harness/testcases/WINNF_FT_S_EPR_testcase.py
  src/harness/testcases/WINNF_FT_S_FPR_testcase.py
  src/harness/testcases/WINNF_FT_S_GPR_testcase.py
  src/harness/testcases/WINNF_FT_S_MCP_testcase.py
  src/harness/testcases/WINNF_FT_S_PPR_testcase.py
Labels: reviewer:federated

#612 Tiny fixes: Var names and import logging
  src/harness/testcases/WINNF_FT_S_DRG_testcase.py
  src/harness/testcases/WINNF_FT_S_EXZ_testcase.py
Labels: reviewer:federated

#614 Changes to reg and grant request - format issue.
  src/harness/testcases/WINNF_FT_S_QPR_testcase.py
Labels: needs reviewer

#604 DPA: Support for DPA absolute check interference
  src/harness/reference_models/common/data.py
  src/harness/reference_models/dpa/dpa_mgr.py
  src/harness/reference_models/dpa/dpa_mgr_example.py
Labels: needs reviewer, reference model

#596 Border: Explicitely using median ITM pathloss
  src/harness/testcases/WINNF_FT_S_BPR_testcase.py
Labels: needs reviewer

#618 Fix unit tests & benchmark on latest code state
  src/harness/reference_models/common/mpool.py
  src/harness/reference_models/dpa/move_list_test.py
  src/harness/reference_models/examples/README.md
  src/harness/reference_models/geo/nlcd_test.py
  src/harness/reference_models/geo/terrain_test.py
  src/harness/reference_models/geo/testutils.py
  src/harness/reference_models/interference/aggregate_interference_test.py
  src/harness/reference_models/ppa/ppa_test.py
  src/harness/reference_models/pre_iap_filtering/fss_purge_test.py
  src/harness/reference_models/pre_iap_filtering/pre_iap_filtering_test.py
  src/harness/reference_models/pre_iap_filtering/zone_purge_test.py
  src/harness/reference_models/propagation/wf_hybrid_test.py
  src/harness/reference_models/propagation/wf_itm_test.py
  src/harness/reference_models/tools/README.md
  src/harness/reference_models/tools/__init__.py
  src/harness/reference_models/tools/benchmark/README.md
  src/harness/reference_models/tools/benchmark/time_dpa.py
  src/harness/reference_models/tools/benchmark/time_prop.py
  src/harness/reference_models/tools/entities.py
  src/harness/reference_models/tools/examples/example_fss_interference.py
  src/harness/reference_models/tools/examples/fss_pointing.py
  src/harness/reference_models/tools/examples/fss_pointing_test.py
  src/harness/reference_models/tools/testutils.py
  src/harness/test_main.py
Labels: needs reviewer, reference model

#621 MCP.1 fixes
  src/harness/reference_models/common/data.py
  src/harness/reference_models/interference/aggregate_interference.py
  src/harness/reference_models/interference/aggregate_interference_example.py
  src/harness/reference_models/interference/aggregate_interference_test.py
  src/harness/reference_models/pre_iap_filtering/pre_iap_util.py
  src/harness/testcases/WINNF_FT_S_GPR_testcase.py
  src/harness/testcases/WINNF_FT_S_MCP_testcase.py
Labels: needs reviewer

#620 Remove unnecessary FAD pull from SAS THs
  src/harness/testcases/WINNF_FT_S_MCP_testcase.py
Labels: needs reviewer

#619 Fix test_WINNF_FT_S_FAD_1
  src/harness/testcases/WINNF_FT_S_FAD_testcase.py
Labels: reviewer:sony

#617 fix GWPZ and PPA data records in testdata
  src/harness/testcases/testdata/gwpz_record_0.json
  src/harness/testcases/testdata/ppa_record_0.json
  src/harness/testcases/testdata/ppa_record_1.json
  src/harness/testcases/testdata/ppa_record_2.json
  src/harness/testcases/testdata/ppa_record_3.json
Labels: reviewer:google

#624 fix injectDatabaseUrl errors
  src/harness/testcases/WINNF_FT_S_FDB_testcase.py
  src/harness/testcases/WINNF_FT_S_WDB_testcase.py
Labels: reviewer:google

#628 Clean openssl config file
  cert/openssl.cnf
Labels: needs reviewer

#630 Update openssl config of SAS cert
  cert/openssl.cnf
  src/harness/certs/generate_fake_certs.sh
Labels: reviewer:google

#634 Add extensive checking of the MCP and xPR configs.
  src/harness/testcases/WINNF_FT_S_EPR_testcase.py
  src/harness/testcases/WINNF_FT_S_FPR_testcase.py
  src/harness/testcases/WINNF_FT_S_GPR_testcase.py
  src/harness/testcases/WINNF_FT_S_MCP_testcase.py
  src/harness/testcases/WINNF_FT_S_PPR_testcase.py
Labels: needs reviewer

#635 Fix unit test broken by recent PR + bug fix
  src/harness/reference_models/interference/test_data/gwpz_0.json
  src/harness/reference_models/interference/test_data/gwpz_1.json
  src/harness/reference_models/interference/test_data/gwpz_2.json
  src/harness/reference_models/interference/test_data/gwpz_ut.json
  src/harness/reference_models/pre_iap_filtering/fss_purge.py
  src/harness/reference_models/pre_iap_filtering/testdata/cbsd_0.json
  src/harness/reference_models/pre_iap_filtering/testdata/cbsd_1.json
  src/harness/reference_models/pre_iap_filtering/testdata/cbsd_2.json
  src/harness/reference_models/pre_iap_filtering/testdata/cbsd_3.json
  src/harness/reference_models/pre_iap_filtering/testdata/cbsd_4.json
  src/harness/reference_models/pre_iap_filtering/testdata/cbsd_5.json
  src/harness/reference_models/pre_iap_filtering/testdata/testset1/cbsd_0.json
  src/harness/reference_models/pre_iap_filtering/testdata/testset1/cbsd_1.json
  src/harness/reference_models/pre_iap_filtering/testdata/testset1/cbsd_2.json
  src/harness/reference_models/pre_iap_filtering/testdata/testset1/cbsd_3.json
  src/harness/reference_models/pre_iap_filtering/testdata/testset1/cbsd_4.json
  src/harness/reference_models/pre_iap_filtering/testdata/testset1/cbsd_5.json
  src/harness/reference_models/pre_iap_filtering/testdata/testset1/cbsd_bkp.json
  src/harness/reference_models/pre_iap_filtering/testdata/testset2/cbsd_0.json
  src/harness/reference_models/pre_iap_filtering/testdata/testset2/cbsd_1.json
  src/harness/reference_models/pre_iap_filtering/testdata/testset2/cbsd_2.json
  src/harness/reference_models/pre_iap_filtering/testdata/testset2/cbsd_3.json
  src/harness/reference_models/pre_iap_filtering/testdata/testset2/cbsd_4.json
  src/harness/reference_models/pre_iap_filtering/testdata/testset2/cbsd_5.json
Labels: needs reviewer, reference model

#638 Names for coastal DPAs need to use the latest naming scheme #625
  src/harness/reference_models/dpa/dpa_mgr.py
  src/harness/reference_models/geo/zones_test.py
  src/harness/testcases/WINNF_FT_S_GRA_testcase.py
  src/harness/testcases/WINNF_FT_S_HBT_testcase.py
  src/harness/testcases/WINNF_FT_S_IPR_testcase.py
  src/harness/testcases/WINNF_FT_S_MCP_testcase.py
  src/harness/testcases/WINNF_FT_S_SIQ_testcase.py
Labels: reviewer:red

#642 Fix mpool to support mono-cpus.
  README.md
  src/harness/reference_models/common/mpool.py
  src/harness/test_main.py
Labels: reference model

#641 Fix PAL record error in PPR_1
  src/harness/testcases/WINNF_FT_S_MCP_testcase.py
Labels: needs reviewer

#644 revert src/harness/testcases/testdata/gwpz_record_0.json back
  src/harness/testcases/testdata/gwpz_record_0.json
Labels: reviewer:google

#648 ITM: Minor fix for multi-compiler support.
  src/harness/reference_models/propagation/itm/its/itm.cpp
Labels: reference model

#645 Update IPR (Issue #626) and MCP to support configs with zero test harnesses
  src/harness/testcases/WINNF_FT_S_IPR_testcase.py
  src/harness/testcases/WINNF_FT_S_MCP_testcase.py
Labels: needs reviewer

#570 E-Hata: Fix effective height issue
  src/harness/reference_models/propagation/ehata/ehata.py
  src/harness/reference_models/propagation/ehata/ehata_test.py
  src/harness/reference_models/propagation/ehata/its/PreprocessTerrainPath.cpp
  src/harness/reference_models/propagation/ehata/its/test/test-inputs-wfmod.csv
  src/harness/reference_models/propagation/wf_hybrid_test.py
Labels: reference model, reviewer:commscope

#656 Reference Model Fixes to support MCP
  src/harness/reference_models/common/data.py
  src/harness/reference_models/interference/aggregate_interference.py
  src/harness/reference_models/pre_iap_filtering/pre_iap_util.py
  src/harness/reference_models/pre_iap_filtering/zone_purge.py
  src/harness/testcases/WINNF_FT_S_MCP_testcase.py
Labels: needs reviewer

#653 fix issue 651 - IAP calculation headroom margin issue
  src/harness/reference_models/iap/iap.py
Labels: reviewer:commscope

#659 Fix PreIAP and Aggregate Interference use of deploymentParam
  src/harness/reference_models/interference/aggregate_interference.py
  src/harness/reference_models/pre_iap_filtering/testdata/gwpz_0.json
  src/harness/reference_models/pre_iap_filtering/testdata/testset1/gwpz_0.json
  src/harness/reference_models/pre_iap_filtering/zone_purge.py
Labels: reviewer:federated

#660 Prevent Domain proxy from causing an exception when heartbeating with zero grants
  src/harness/test_harness_objects.py
Labels: reviewer:federated

#658 Clean code by introducing new functions in util.py
  README.md
  src/harness/README.md
  src/harness/sas_test_harness.py
  src/harness/security_testcase.py
  src/harness/testcases/WINNF_FT_S_EPR_testcase.py
  src/harness/testcases/WINNF_FT_S_FAD_testcase.py
  src/harness/testcases/WINNF_FT_S_FDB_testcase.py
  src/harness/testcases/WINNF_FT_S_FPR_testcase.py
  src/harness/testcases/WINNF_FT_S_GPR_testcase.py
  src/harness/testcases/WINNF_FT_S_GRA_testcase.py
  src/harness/testcases/WINNF_FT_S_IPR_testcase.py
  src/harness/testcases/WINNF_FT_S_MCP_testcase.py
  src/harness/testcases/WINNF_FT_S_PCR_testcase.py
  src/harness/testcases/WINNF_FT_S_PPR_testcase.py
  src/harness/testcases/WINNF_FT_S_SCS_testcase.py
  src/harness/testcases/WINNF_FT_S_SDS_testcase.py
  src/harness/testcases/WINNF_FT_S_SIQ_testcase.py
  src/harness/testcases/WINNF_FT_S_SSS_testcase.py
  src/harness/testcases/WINNF_FT_S_WDB_testcase.py
  src/harness/util.py
Labels: needs reviewer

#662 IAP: bug fixes and cleanup
  src/harness/reference_models/common/data.py
  src/harness/reference_models/iap/iap.py
  src/harness/reference_models/iap/iap_example.py
  src/harness/reference_models/interference/interference.py
Labels: needs reviewer, reference model

#664 Aggregate interference: Cleanup and bug fix
  src/harness/reference_models/interference/aggregate_interference.py
  src/harness/reference_models/interference/interference.py
Labels: needs reviewer, reference model

#663 tiny fix of import in PCR test cases
  src/harness/testcases/WINNF_FT_S_PCR_testcase.py
Labels: reviewer:google

#670 Cert generation script for SAS UUTs
  src/harness/certs/generate_sas_cert.sh
Labels: needs reviewer

#669 Fix WDB test cases
  src/harness/testcases/WINNF_FT_S_WDB_testcase.py
Labels: needs reviewer

#666 IPR testcase pulls FAD with test harness cert
  src/harness/testcases/WINNF_FT_S_IPR_testcase.py
Labels: reviewer:federated

#672 Fix minor bugs in MCP workflow
  src/harness/reference_models/interference/aggregate_interference.py
  src/harness/sas_testcase.py
  src/harness/testcases/WINNF_FT_S_MCP_testcase.py
Labels: reviewer:federated

#673 Add a missing zero to grant_3
  src/harness/testcases/testdata/grant_3.json
Labels: needs reviewer

#665 filterChannelsByFrequencyRange fix
  src/harness/util.py
Labels: reviewer:google

#671 Fix for AMSL not taken into account (PPA creation, BPR, QPR and PAT)
  src/harness/reference_models/ppa/ppa.py
  src/harness/reference_models/tools/testutils.py
  src/harness/testcases/WINNF_FT_S_BPR_testcase.py
  src/harness/testcases/WINNF_FT_S_PAT_testcase.py
  src/harness/testcases/WINNF_FT_S_QPR_testcase.py
Labels: needs reviewer, reference model

#674 Changes to PPAcreation so API is more permissive
  src/harness/sas_testcase.py
Labels: reviewer:google

#679 PPA Assert Failure adding ability for SUUT to fail right away (PCR4 and PCR5)
  src/harness/sas_testcase.py
  src/harness/testcases/WINNF_FT_S_PCR_testcase.py
Labels: reviewer:google

#681 Assert high frequency for IAP FSS co-channel
  src/harness/reference_models/iap/iap.py
Labels: reviewer:google

#675 DPA builder: Cleanup and small bug fixes
  data/ntia/E-DPAs.kml
  src/harness/reference_models/dpa/dpa_builder.py
  src/harness/reference_models/dpa/dpa_mgr.py
  src/harness/reference_models/dpa/dpa_mgr_example.py
  src/harness/reference_models/dpa/test_data/points_alameda.json
  src/harness/reference_models/tools/benchmark/time_dpa.py
Labels: needs reviewer, reference model

#682 Fix broken PAT following missing nlcd_driver reference
  src/harness/testcases/WINNF_FT_S_PAT_testcase.py
Labels: reviewer:sony

#678 Fix schema validation: could failed on network filesystem.
  src/harness/util.py
Labels: needs reviewer

#683 DPA: Remove debug trace
  src/harness/reference_models/dpa/dpa_builder.py
Labels: reference model, reviewer:nist

#677 Add more logging to the test harness.
  src/harness/testcases/WINNF_FT_S_MCP_testcase.py
Labels: needs reviewer

#676 Generate certs for each CBSD in testdata, use these in MCP/xPR default configs
  cert/openssl.cnf
  src/harness/certs/generate_fake_certs.sh
  src/harness/testcases/WINNF_FT_S_EPR_testcase.py
  src/harness/testcases/WINNF_FT_S_FPR_testcase.py
  src/harness/testcases/WINNF_FT_S_GPR_testcase.py
  src/harness/testcases/WINNF_FT_S_MCP_testcase.py
  src/harness/testcases/WINNF_FT_S_PPR_testcase.py
Labels: needs reviewer, reviewer:red

#687 Fix GRA.13 to check lessEqual instead of less
  src/harness/testcases/WINNF_FT_S_GRA_testcase.py
Labels: needs reviewer

#649 fix SIQ.3 C2 and C4 checking
  src/harness/sas_testcase.py
  src/harness/testcases/WINNF_FT_S_SIQ_testcase.py
  src/harness/testcases/helper_unit_testcase.py
Labels: reviewer:commscope, reviewer:google

#694 Fix for Issue #693 (Fix C1 in SIQ.3)
  src/harness/testcases/WINNF_FT_S_SIQ_testcase.py
Labels: needs reviewer

#695 DPA: Update with latest KML and format changes.
  data/ntia/E-DPAs.kml
  data/ntia/E-DPAs_CatBNeighborhoods.csv
  data/ntia/P-DPAs.kml
  data/ntia/P-DPAs_CatBNeighborhoods.csv
  src/harness/reference_models/dpa/dpa_mgr.py
  src/harness/reference_models/geo/zones.py
Labels: needs reviewer, reference model

#702 FSS mask: alternative proposal to fix FSS mask loss.
  src/harness/reference_models/interference/interference.py
  src/harness/reference_models/interference/interference_test.py
Labels: needs reviewer, reference model

#703 Fix syntax error in helper_unit_testcase.py
  src/harness/testcases/helper_unit_testcase.py
Labels: needs reviewer

#707 Add more logging to the test harness.
  src/harness/reference_models/dpa/move_list.py
  src/harness/reference_models/interference/aggregate_interference.py
  src/harness/reference_models/interference/interference.py
  src/harness/reference_models/ppa/ppa.py
  src/harness/reference_models/pre_iap_filtering/fss_purge.py
  src/harness/reference_models/pre_iap_filtering/inter_sas_duplicate_grant.py
  src/harness/reference_models/pre_iap_filtering/pre_iap_filtering.py
  src/harness/reference_models/pre_iap_filtering/zone_purge.py
  src/harness/sas_test_harness.py
Labels: reviewer:commscope

#709 Fix propagation segmentation fault when Tx & Rx location identical.
  src/harness/reference_models/interference/interference.py
  src/harness/reference_models/propagation/wf_hybrid.py
  src/harness/reference_models/propagation/wf_hybrid_test.py
  src/harness/reference_models/propagation/wf_itm.py
  src/harness/reference_models/propagation/wf_itm_test.py
Labels: needs reviewer, reference model

#713 Tiny update of PCR tests to use feature collection
  src/harness/testcases/WINNF_FT_S_PCR_testcase.py
Labels: reviewer:google

#715 fix issue #705 - signal alarm not cleaned up on test error
  src/harness/full_activity_dump_helper.py
  src/harness/sas_testcase.py
  src/harness/testcases/WINNF_FT_S_PCR_testcase.py
Labels: reviewer:google

#719 Minor fix issue caused by recent addition of logging.
  src/harness/reference_models/interference/interference.py
Labels: reference model, reviewer:commscope, reviewer:federated

#706 DPA: update to comply with latest spec
  src/harness/reference_models/dpa/dpa_mgr.py
  src/harness/reference_models/dpa/dpa_mgr_example.py
  src/harness/reference_models/dpa/move_list.py
  src/harness/reference_models/dpa/move_list_example.py
  src/harness/reference_models/dpa/move_list_test.py
  src/harness/reference_models/geo/zones.py
  src/harness/reference_models/geo/zones_test.py
Labels: reference model, reviewer:federated, reviewer:nist

#690 Add multi threading to MCP steps that can be run in parallel
  src/harness/full_activity_dump_helper.py
  src/harness/sas_testcase.py
  src/harness/testcases/WINNF_FT_S_MCP_testcase.py
Labels: reviewer:commscope

#714 fix issue #704
  src/harness/testcases/WINNF_FT_S_IPR_testcase.py
Labels: reviewer:google

#697 Fix MCP by computing ESC interference post-filter
  src/harness/reference_models/iap/iap.py
  src/harness/reference_models/interference/aggregate_interference.py
  src/harness/reference_models/interference/interference.py
Labels: reference model, reviewer:commscope, reviewer:federated

#716 IAP/AggInterf: insure the protection channel aligned to multiple of 5MHz
  src/harness/reference_models/interference/aggregate_interference.py
  src/harness/reference_models/interference/interference.py
  src/harness/reference_models/interference/interference_test.py
Labels: reference model, reviewer:federated

#717 FSS cochannel: support partial overlap with grant
  src/harness/reference_models/interference/interference.py
  src/harness/reference_models/interference/interference_test.py
Labels: reference model, reviewer:federated

#720 Remove/replace some of the logging.
  src/harness/reference_models/interference/aggregate_interference.py
  src/harness/reference_models/interference/interference.py
Labels: reference model, reviewer:federated

#718 Fix for getFqdnLocalhost()/getUnusedPort()
  src/harness/database.py
  src/harness/sas_test_harness.py
  src/harness/test.cfg
  src/harness/util.py
  src/harness/util_test.py
Labels: needs reviewer

#722 fix issue #721 part [1]
  src/harness/reference_models/pre_iap_filtering/testdata/gwpz_0.json
  src/harness/reference_models/pre_iap_filtering/zone_purge.py
Labels: reviewer:google

#723 fix the datetime missing error
  src/harness/testcases/WINNF_FT_S_PCR_testcase.py
Labels: reviewer:google

#726 small update of FAD_1 to remove check of PPA creator value
  src/harness/testcases/WINNF_FT_S_FAD_testcase.py
Labels: reviewer:google

#727 Fix MCP.1 race condition
  src/harness/testcases/WINNF_FT_S_MCP_testcase.py
Labels: reviewer:federated

#725 Fixes checkForOverlappingGrants() issue #724
  src/harness/reference_models/pre_iap_filtering/pre_iap_util.py
  src/harness/reference_models/pre_iap_filtering/pre_iap_util_test.py
Labels: reviewer:federated

#730 Update of DPA and Exclusion Zone
  data/ntia/E-DPAs.kml
  data/ntia/GB_Part90_EZ.kml
  src/harness/reference_models/geo/zones.py
Labels: reviewer:federated

#729 Fixes getPpaFrequencyRange() issue #728
  src/harness/reference_models/pre_iap_filtering/pre_iap_util.py
  src/harness/reference_models/pre_iap_filtering/pre_iap_util_test.py
Labels: reviewer:federated

#731 Remove multiprocess Manager
  src/harness/reference_models/common/mpool.py
  src/harness/reference_models/iap/iap.py
  src/harness/reference_models/interference/aggregate_interference.py
  src/harness/reference_models/interference/interference.py
  src/harness/reference_models/tools/benchmark/prof_agg_interf.py
  src/harness/reference_models/tools/benchmark/prof_prop.py
  src/harness/reference_models/tools/profpool.py
Labels: reference model, reviewer:federated

#732 Add memoizing propag cache around repeated calculations.
  src/harness/reference_models/iap/iap.py
  src/harness/reference_models/interference/aggregate_interference.py
Labels: reference model, reviewer:federated

#733 Update with latest DPA and exclusion zone.
  data/ntia/E-DPAs.kml
  data/ntia/GB_Part90_EZ.kml
  data/ntia/P-DPAs.kml
  src/harness/reference_models/geo/zones.py
  src/harness/reference_models/geo/zones_test.py
Labels: reference model
