Repository Wireless-Innovation-Forum/Spectrum-Access-System, pull requests merged in 2018-02, with the labels that each got.

#412 Update siq 4 and helper fuction
  src/harness/sas_testcase.py
  src/harness/testcases/WINNF_FT_S_SIQ_testcase.py
  src/harness/testcases/helper_unit_testcase.py
Labels: reviewer:google

#419 Updated the Make PPA and PAL Consistent Function
  src/harness/util.py
Labels: reviewer:google

#422 Fixed Input Params in makePpaAndPalRecordsConsistent
  src/harness/util.py
Labels: reviewer:red

#408 New DRG test case using new ID: 6
  src/harness/testcases/WINNF_FT_S_DRG_testcase.py
  src/harness/testcases/configs/test_WINNF_FT_S_DRG_6/default.config
  src/harness/util.py
Labels: reviewer:federated

#364 NEW SCS testcases: SCS 6 to 10
  cert/openssl.cnf
  src/harness/certs/README.md
  src/harness/certs/generate_fake_certs.sh
  src/harness/fake_sas.py
  src/harness/security_testcase.py
  src/harness/testcases/WINNF_FT_S_SCS_testcase.py
Labels: reviewer:google

#371 Federated Wireless submitted test cases SCS.12, SCS.13, SCS.14,SCS.15
  cert/openssl.cnf
  src/harness/certs/README.md
  src/harness/certs/generate_fake_certs.sh
  src/harness/sas_testcase.py
  src/harness/security_testcase.py
  src/harness/testcases/WINNF_FT_S_SCS_testcase.py
  src/harness/testcases/configs/test_WINNF_FT_S_SCS_17/default.config
  src/harness/testcases/configs/test_WINNF_FT_S_SCS_18/default.config
  src/harness/testcases/configs/test_WINNF_FT_S_SCS_19/default.config
  src/harness/testcases/configs/test_WINNF_FT_S_SCS_20/default.config
  src/harness/util.py
Labels: reviewer:google

#400 NEW REG test case using new ID: 12.
  src/harness/testcases/WINNF_FT_S_REG_testcase.py
  src/harness/testcases/configs/test_WINNF_FT_S_REG_12/default.config
Labels: reviewer:federated

#401 NEW HBT test case using new ID: 11
  src/harness/testcases/WINNF_FT_S_HBT_testcase.py
Labels: reviewer:federated

#423 Cleanup example code by migrating in the fss_pointing code.
  src/harness/reference_models/examples/README.md
  src/harness/reference_models/examples/entities.py
  src/harness/reference_models/examples/example_fss_interference.py
  src/harness/reference_models/examples/fss_pointing.py
  src/harness/reference_models/examples/fss_pointing_test.py
Labels: reviewer:federated

#424 clean up not-yet-needed configure files for SCS.17-20 to be submitted…
  src/harness/testcases/configs/test_WINNF_FT_S_SCS_17/default.config
  src/harness/testcases/configs/test_WINNF_FT_S_SCS_18/default.config
  src/harness/testcases/configs/test_WINNF_FT_S_SCS_19/default.config
  src/harness/testcases/configs/test_WINNF_FT_S_SCS_20/default.config
Labels: needs reviewer

#285 DPA move list reference code
  src/harness/reference_models/move_list_calc/README.md
  src/harness/reference_models/move_list_calc/move_list.py
  src/harness/reference_models/move_list_calc/move_list_example.py
  src/harness/reference_models/move_list_calc/test_data/GrantRequest_1.json
  src/harness/reference_models/move_list_calc/test_data/GrantRequest_2.json
  src/harness/reference_models/move_list_calc/test_data/GrantRequest_3.json
  src/harness/reference_models/move_list_calc/test_data/GrantRequest_4.json
  src/harness/reference_models/move_list_calc/test_data/GrantRequest_5.json
  src/harness/reference_models/move_list_calc/test_data/GrantRequest_6.json
  src/harness/reference_models/move_list_calc/test_data/RegistrationRequest_1.json
  src/harness/reference_models/move_list_calc/test_data/RegistrationRequest_2.json
  src/harness/reference_models/move_list_calc/test_data/RegistrationRequest_3.json
  src/harness/reference_models/move_list_calc/test_data/RegistrationRequest_4.json
  src/harness/reference_models/move_list_calc/test_data/RegistrationRequest_5.json
  src/harness/reference_models/move_list_calc/test_data/RegistrationRequest_6.json
  src/harness/reference_models/move_list_calc/test_data/protection_zones.kml
Labels: reference model, reviewer:commscope, reviewer:federated, reviewer:google

#421 fix logging handler being added every time a test case is invoked
  src/harness/util.py
Labels: reviewer:google

#253 Added PPA Reference Model
  .gitignore
  README.md
  schema/HeartbeatRequestExample.json
  schema/PalRecord.schema.json
  schema/PalRecordExample.json
  schema/RegistrationRequest.schema.json
  schema/RegistrationRequestExample.json
  schema/RegistrationRequestExample2.json
  schema/verify_schema.py
  src/harness/reference_models/geo/CONFIG.py
  src/harness/reference_models/geo/census_tract.py
  src/harness/reference_models/ppa/__init__.py
  src/harness/reference_models/ppa/ppa.py
  src/harness/reference_models/ppa/ppa_example.py
  src/harness/reference_models/ppa/test_data/123456789.json
  src/harness/reference_models/ppa/test_data/device_a.json
  src/harness/reference_models/ppa/test_data/pal_record_0.json
  src/harness/sas_testcase.py
  src/harness/util.py
Labels: reference model, reviewer:google

#357 NEW REG test case using new ID: 7
  src/harness/testcases/WINNF_FT_S_REG_testcase.py
Labels: reviewer:federated

#418 Fix RLQ_1 per latest revision
  src/harness/testcases/WINNF_FT_S_RLQ_testcase.py
Labels: reviewer:commscope

#407 NEW RLQ testcase using new ID: 6
  src/harness/testcases/WINNF_FT_S_RLQ_testcase.py
  src/harness/testcases/configs/test_WINNF_FT_S_RLQ_6/default.config
  src/harness/util.py
Labels: reviewer:federated

#425 revised SDS.6,7,8,9,10,12,13,14,15 based on approved corresponding SCS test cases
  cert/openssl.cnf
  src/harness/certs/README.md
  src/harness/certs/generate_fake_certs.sh
  src/harness/testcases/WINNF_FT_S_SDS_testcase.py
Labels: reviewer:commscope, reviewer:google

#432 Check config before preloading REG conditionals.
  src/harness/testcases/WINNF_FT_S_REG_testcase.py
Labels: reviewer:federated

#434 fix the wrong certificate type for SCS.10 and SDS.10 per Comscope review comments
  cert/openssl.cnf
  src/harness/certs/generate_fake_certs.sh
Labels: reviewer:commscope

#420 NEW HBT test case using new ID: 12
  src/harness/testcases/WINNF_FT_S_HBT_testcase.py
Labels: reviewer:federated

#428 NEW SIQ test case with new ID: 3
  src/harness/testcases/WINNF_FT_S_SIQ_testcase.py
  src/harness/util.py
Labels: reviewer:federated

#438 Add support of GeoJSON gemetries in areas routines.
  src/harness/reference_models/geo/testdata/json/ppa_record_0.json
  src/harness/reference_models/geo/testdata/json/test_geocollection.json
  src/harness/reference_models/geo/utils.py
  src/harness/reference_models/geo/utils_test.py
  src/harness/util.py
Labels: reviewer:federated

#409 NEW HBT test case using new ID: 10.
  src/harness/testcases/WINNF_FT_S_HBT_testcase.py
  src/harness/testcases/configs/test_WINNF_FT_S_HBT_10/default.config
  src/harness/util.py
Labels: reviewer:federated

#445 Fix issue with POST/GET in sas.py
  src/harness/sas.py
Labels: needs reviewer

#429 NEW GRA testcase using new ID: 17
  src/harness/testcases/WINNF_FT_S_GRA_testcase.py
  src/harness/testcases/configs/test_WINNF_FT_S_GRA_17/default.config
Labels: reviewer:federated

#437 # update PPA record2 coordinates to be CCW
  src/harness/testcases/testdata/ppa_record_2.json
Labels: reviewer:google

#442 Add a new utility routine GridPolygon().
  src/harness/reference_models/geo/utils.py
  src/harness/reference_models/geo/utils_test.py
Labels: reference model, reviewer:commscope

#446 Remove all test cases which use the old IDs
  src/harness/testcases/README.md
  src/harness/testcases/deregistration_testcase.py
  src/harness/testcases/grant_testcase.py
  src/harness/testcases/heartbeat_testcase.py
  src/harness/testcases/registration_testcase.py
  src/harness/testcases/relinquishment_testcase.py
  src/harness/testcases/spectrum_inquiry_testcase.py
Labels: reviewer:federated

#449 Update geo utilities for robustness
  src/harness/reference_models/geo/utils.py
  src/harness/reference_models/geo/utils_test.py
Labels: reference model

#444 Use the installationParam object from SAS-CBSD 2.0
  src/harness/testcases/testdata/esc_sensor_record_0.json
Labels: reviewer:federated
