Repository Wireless-Innovation-Forum/Spectrum-Access-System, pull requests merged in 2018-07, with the labels that each got.

#777 Paul from red fixed incorrect code in sas_testcase.py
  src/harness/sas_testcase.py
Labels: needs reviewer

#778 Fixes the default config for IPR_5
  src/harness/testcases/WINNF_FT_S_IPR_testcase.py
Labels: reviewer:federated

#779 Update the IPR.7 testcase to not require a portal DPA DB config...
  src/harness/testcases/WINNF_FT_S_IPR_testcase.py
Labels: needs reviewer

#781 PPR_1 default config file update
  src/harness/testcases/WINNF_FT_S_PPR_testcase.py
Labels: reviewer:google

#783 Update the MES.2 test case to remove CBSD #5 as requested by WG4.
  src/harness/testcases/WINNF_FT_S_MES_testcase.py
Labels: reviewer:red

#784 Refactor assertTlsHandshake{Succeed,Failure} into a common function.
  src/harness/security_testcase.py
Labels: reviewer:red

#786 FDB.6: Skip Relinquishment in case of Interference Response in Grant
  src/harness/testcases/WINNF_FT_S_FDB_testcase.py
Labels: reviewer:google

#785 Update BPR.2 to only check Grants which at least partially overlap 36…
  src/harness/testcases/WINNF_FT_S_BPR_testcase.py
Labels: needs reviewer

#789 Minor numerical correction in QPR testcase
  src/harness/testcases/WINNF_FT_S_QPR_testcase.py
Labels: reviewer:sony
