Repository Wireless-Innovation-Forum/Spectrum-Access-System, pull requests merged in 2018-09, with the labels that each got.

#802 Fix DPA manager to have coherent state always.
  src/harness/reference_models/dpa/dpa_mgr.py
  src/harness/reference_models/dpa/dpa_mgr_example.py
Labels: needs reviewer, reference model

#805 Fix miscellaneous bugs in domain proxy
  src/harness/test_harness_objects.py
Labels: reviewer:sony

#807 Domain proxy batching of registration and heartbeat
  src/harness/test_harness_objects.py
Labels: reviewer:red

#808 Fix FSS purge list: MCBSD should be for the 5MHz target band.
  src/harness/reference_models/pre_iap_filtering/fss_purge.py
Labels: reference model, reviewer:commscope

#806 Make base_url a parameter to assertTlsHandshakeFailure().
  src/harness/security_testcase.py
  src/harness/testcases/WINNF_FT_S_SCS_testcase.py
  src/harness/testcases/WINNF_FT_S_SDS_testcase.py
  src/harness/testcases/WINNF_FT_S_SSS_testcase.py
Labels: reviewer:red

#812 Introduce a flag to turn on/off early-exit in PAT
  src/harness/testcases/WINNF_FT_S_PAT_testcase.py
Labels: reviewer:red

#810 Whitelist fccIds by injecting before FAD
  src/harness/sas_testcase.py
  src/harness/testcases/WINNF_FT_S_FAD_testcase.py
  src/harness/testcases/WINNF_FT_S_GRA_testcase.py
  src/harness/testcases/WINNF_FT_S_MCP_testcase.py
Labels: reviewer:google

#809 Fix time zone issue in FDB.8
  src/harness/testcases/WINNF_FT_S_FDB_testcase.py
Labels: reviewer:sony

#811 Update MCP testcase to ignore failed registrations
  src/harness/test_harness_objects.py
Labels: reviewer:commscope
