Repository Wireless-Innovation-Forum/Spectrum-Access-System, pull requests merged in 2018-11, with the labels that each got.

#841 Add TCP keepalive to all test harness requests
  src/harness/request_handler.py
Labels: reviewer:sony

#837 DPA: Add new modes for DPA margin.
  src/harness/reference_models/dpa/dpa_mgr.py
  src/harness/reference_models/dpa/dpa_mgr_example.py
Labels: reference model

#842 Improve portability of JSON schema checking code
  src/harness/util.py
Labels: reviewer:sony

#839 # Filter FSS with high frequency below 3700 MHz for purge list calculation
  src/harness/reference_models/pre_iap_filtering/fss_purge.py
Labels: reviewer:google

#843 Wait until the very end to fail tests which check aggregate interference to DPAs
  src/harness/testcases/WINNF_FT_S_IPR_testcase.py
  src/harness/testcases/WINNF_FT_S_MCP_testcase.py
Labels: reviewer:sony

#844 Peer fccid injection for IPR testcases
  src/harness/testcases/WINNF_FT_S_IPR_testcase.py
Labels: reviewer:google

#833 Simulation only: DPA margin script & simulation utilities
  src/harness/reference_models/tools/sim_utils.py
  src/harness/reference_models/tools/studies/data/ipr7_1kCBSDs.config
  src/harness/reference_models/tools/studies/data/onePoint_P_DPA.kml
  src/harness/reference_models/tools/studies/dpa_margin_sim.py
Labels: reviewer:red

#845 fix MCP injection of gwbl records
  src/harness/testcases/WINNF_FT_S_MCP_testcase.py
Labels: reviewer:google

#847 Fix mem Leak on ITM
  src/harness/reference_models/propagation/itm/itm_its_py.cpp
Labels: needs reviewer, reference model, reviewer:commscope

#846 DPA simulator: update with scatter plot ability
  .gitignore
  src/harness/reference_models/dpa/dpa_mgr.py
  src/harness/reference_models/tools/README.md
  src/harness/reference_models/tools/benchmark/README.md
  src/harness/reference_models/tools/sim_utils.py
  src/harness/reference_models/tools/studies/data/East13_reg_grant.json.zip
  src/harness/reference_models/tools/studies/data/East1_reg_grant.json.zip
  src/harness/reference_models/tools/studies/data/Pensacola_reg_grant.json.zip
  src/harness/reference_models/tools/studies/data/Webster Field_reg_grant.json.zip
  src/harness/reference_models/tools/studies/data/West14_reg_grant.json.zip
  src/harness/reference_models/tools/studies/data/West1_reg_grant.json.zip
  src/harness/reference_models/tools/studies/dpa_margin_sim.py
Labels: reviewer:red

#852 PCR - add buffering to remove gaps between census tracts ( fixes #814 )
  ContributorAgreements/Key Bridge Wireless - CLA.PDF
  src/harness/reference_models/ppa/ppa.py
  src/harness/testcases/WINNF_FT_S_PCR_testcase.py
Labels: reviewer:google

#857 for FAD_1, consider lat and lng equal if same to 6 decimal places ( Fixes #822 )
  src/harness/testcases/WINNF_FT_S_FAD_testcase.py
Labels: reviewer:google

#855 Tiny fix to treat not handledFSS Scenario
  src/harness/testcases/WINNF_FT_S_MCP_testcase.py
Labels: reviewer:google

#856 Remove obsolete census file.
  data/census_tracts/20063955200.json
Labels: reviewer:red

#858 Revert "PCR - add buffering to remove gaps between census tracts ( fixes #814 )"
  src/harness/reference_models/ppa/ppa.py
  src/harness/testcases/WINNF_FT_S_PCR_testcase.py
Labels: reviewer:red

#859 update if PPA cbsd_reference_id is empty array in sas_test_harness.py generatePpaRecords()
  src/harness/sas_test_harness.py
Labels: reviewer:google

#854 DPA: improve logs for enabling post processing eval
  src/harness/reference_models/dpa/dpa_mgr.py
  src/harness/reference_models/dpa/move_list.py
  src/harness/test_main.py
Labels: reference model, reviewer:red

#860 small fix of move list when CBSD position is at same location of the protected point
  src/harness/reference_models/propagation/wf_itm.py
Labels: reference model, reviewer:google

#861 Relax the checks on xPR configs (still matches spec)
  src/harness/testcases/WINNF_FT_S_MCP_testcase.py
Labels: reviewer:commscope
